name: Build docker image
on:
  push:
    branches:
      - hosted
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup env
      run: |
        echo "::set-env name=CONTAINER_IMAGE::docker.pkg.github.com/${GITHUB_REPOSITORY,,}/${GITHUB_REPOSITORY##*/}:${{github.sha}}"
        echo "::set-env name=CONTAINER_IMAGE_LATEST::docker.pkg.github.com/${GITHUB_REPOSITORY,,}/${GITHUB_REPOSITORY##*/}:latest"
    - name: Docker build
      run: |
        docker login -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}} docker.pkg.github.com
        docker build -t $CONTAINER_IMAGE -t $CONTAINER_IMAGE_LATEST .
    - name: Docker push
      run: |
        docker push $CONTAINER_IMAGE
        docker push $CONTAINER_IMAGE_LATEST
