name: Docker publish
on:
  push:
    branches:
      - hosted
env:
  CONTAINER_IMAGE: ghcr.io/${{github.repository}}:${{github.sha}}
  CONTAINER_IMAGE_LATEST: ghcr.io/${{github.repository}}:latest
jobs:
  publish:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
      - name: Build
        run: docker build -t $CONTAINER_IMAGE -t $CONTAINER_IMAGE_LATEST .
      - name: Login
        run: docker login -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}} ghcr.io
      - name: Publish
        run: |
          docker push $CONTAINER_IMAGE
          docker push $CONTAINER_IMAGE_LATEST
